import type { Dispatch } from 'react';
import { ArrowLeftRight, ArrowUp, Home, Layers3, Mountain, Move, RotateCcw, RotateCw, Ruler, Square } from '../../ui/icons/runtime-icons.generated';
import type { GameplayUiAction, GameplayUiState } from '../../app/ui-state';
import { PlacementActionBar, type PlacementModeGroup, type PlacementQuickAction } from '../placement/PlacementActionBar';
import type { MotionPhase } from '../../ui/motion';
interface DockProps{state:GameplayUiState;motionPhase?:MotionPhase;dispatch:Dispatch<GameplayUiAction>;onComplete:()=>void;onCancel:()=>void;}
export function BuildingPlacementDock({state,motionPhase='steady',dispatch,onComplete,onCancel}:DockProps){
const terrainGroup:PlacementModeGroup={id:'terrain',label:'地形处理方式',items:[{id:'balanced-earthwork',label:'平衡挖填',icon:Mountain,active:state.buildingTerrainMode==='balanced-earthwork',onClick:()=>dispatch({type:'SET_BUILDING_TERRAIN_MODE',mode:'balanced-earthwork'})},{id:'fill-only',label:'只填不挖',icon:ArrowUp,active:state.buildingTerrainMode==='fill-only',onClick:()=>dispatch({type:'SET_BUILDING_TERRAIN_MODE',mode:'fill-only'})},{id:'manual-elevation',label:'手动标高',icon:Ruler,active:state.buildingTerrainMode==='manual-elevation',onClick:()=>dispatch({type:'SET_BUILDING_TERRAIN_MODE',mode:'manual-elevation'})}]};
const all=[{id:'position',label:'位置调整',icon:Move,active:state.adjustmentMode==='position',disabled:false,onClick:()=>dispatch({type:'SET_ADJUSTMENT_MODE',mode:'position' as const})},{id:'massing',label:'楼身调整',icon:Layers3,active:state.adjustmentMode==='massing',disabled:false,onClick:()=>dispatch({type:'SET_ADJUSTMENT_MODE',mode:'massing' as const})},{id:'roof',label:'屋顶调整',icon:Home,active:state.adjustmentMode==='roof',disabled:false,onClick:()=>dispatch({type:'SET_ADJUSTMENT_MODE',mode:'roof' as const})},{id:'facade',label:'立面调整尚未开放',icon:Square,active:false,disabled:true,onClick:()=>undefined}];
const adjustmentGroup:PlacementModeGroup={id:'adjustment',label:'建筑调整对象',items:state.buildingEditIntent==='edit'?all.slice(1):all};
const modeGroups:PlacementModeGroup[]=state.buildingEditIntent==='move'?[terrainGroup]:state.buildingEditIntent==='edit'?[adjustmentGroup]:[terrainGroup,adjustmentGroup];
const quickActions:PlacementQuickAction[]=state.buildingEditIntent==='edit'?[]:[{id:'rotate-left',label:'逆时针旋转',icon:RotateCcw,onClick:()=>dispatch({type:'MARK_HISTORY_DIRTY'})},{id:'rotate-right',label:'顺时针旋转',icon:RotateCw,onClick:()=>dispatch({type:'MARK_HISTORY_DIRTY'})},{id:'mirror',label:'镜像建筑',icon:ArrowLeftRight,onClick:()=>dispatch({type:'MARK_HISTORY_DIRTY'})}];
const i=state.buildingEditIntent;const aria=i==='move'?'移动建筑操作栏':i==='edit'?'编辑建筑操作栏':'建筑放置操作栏';const confirm=i==='move'?'完成移动':i==='edit'?'完成编辑':'完成';const cancel=i==='move'?'取消移动':i==='edit'?'取消编辑':'取消';
return <div className={'tool-bottom-cluster building-placement-toolbar-cluster motion-bottom-surface is-'+motionPhase} aria-label={aria} aria-busy={motionPhase!=='steady'}><PlacementActionBar ariaLabel={aria} modeGroups={modeGroups} quickActions={quickActions} confirmLabel={confirm} cancelLabel={cancel} onConfirm={onComplete} onCancel={onCancel}/></div>;}
