import type { BlueprintDockCategory } from '../app/ui-state';

export type BlueprintSize = 'all' | 'small' | 'medium' | 'large';
export type BlueprintSource = 'all' | 'system' | 'workshop' | 'mine';

export interface BlueprintWorkspaceItem {
  id: string;
  name: string;
  category: Exclude<BlueprintDockCategory, 'all'>;
  size: Exclude<BlueprintSize, 'all'>;
  source: Exclude<BlueprintSource, 'all'>;
  footprint: string;
  objectCount: number;
  estimatedCost: string;
  description: string;
  previewAsset: string;
  previewPosition: string;
  previewSize: string;
}

export const BLUEPRINT_CATEGORY_LABELS: Record<BlueprintDockCategory, string> = {
  all: '全部蓝图',
  residential: '民居蓝图',
  commercial: '商业蓝图',
  workshop: '工坊蓝图',
  administration: '管理蓝图',
  science: '科学蓝图',
  faith: '信仰蓝图',
  military: '军事蓝图',
  palace: '宫殿蓝图',
};

export const BLUEPRINT_SIZE_LABELS: Record<BlueprintSize, string> = {
  all: '全部',
  small: '小型',
  medium: '中型',
  large: '大型',
};

export const BLUEPRINT_SOURCE_LABELS: Record<BlueprintSource, string> = {
  all: '全部',
  system: '系统内置',
  workshop: '创意工坊',
  mine: '我的蓝图',
};

export const BLUEPRINT_WORKSPACE_ITEMS: readonly BlueprintWorkspaceItem[] = [
  {
    id: 'bp-residential-jiangnan-courtyard',
    name: '江南二进院',
    category: 'residential',
    size: 'medium',
    source: 'system',
    footprint: '12 × 18',
    objectCount: 18,
    estimatedCost: '8,420 钱',
    description: '两进院落组织正房、厢房、院墙与基础庭院绿化，适合连续布置在江南街巷内部。',
    previewAsset: '/assets/wanhu-gameplay-city.png',
    previewPosition: '25% 58%',
    previewSize: '520px auto',
  },
  {
    id: 'bp-residential-riverside-home',
    name: '临河小院',
    category: 'residential',
    size: 'small',
    source: 'workshop',
    footprint: '8 × 12',
    objectCount: 11,
    estimatedCost: '4,180 钱',
    description: '紧凑的一进临水住居，保留短院墙、树木和河岸留白，适合填补滨水街区的小地块。',
    previewAsset: '/assets/wanhu-gameplay-lake.png',
    previewPosition: '65% 55%',
    previewSize: '500px auto',
  },
  {
    id: 'bp-commercial-front-shop',
    name: '前店后宅',
    category: 'commercial',
    size: 'medium',
    source: 'system',
    footprint: '10 × 16',
    objectCount: 15,
    estimatedCost: '7,260 钱',
    description: '沿街铺面与后院住居组成的商住组合，适合连续排列形成主要商业街界面。',
    previewAsset: '/assets/wanhu-gameplay-city.png',
    previewPosition: '48% 46%',
    previewSize: '540px auto',
  },
  {
    id: 'bp-commercial-street-row',
    name: '临街商铺组',
    category: 'commercial',
    size: 'large',
    source: 'mine',
    footprint: '18 × 22',
    objectCount: 27,
    estimatedCost: '13,900 钱',
    description: '四间临街商铺、后场和小型装卸空间组成的商业组团，用于快速生成完整街角。',
    previewAsset: '/assets/wanhu-main-menu.png',
    previewPosition: '58% 45%',
    previewSize: '560px auto',
  },
  {
    id: 'bp-workshop-dye-yard',
    name: '染坊作院',
    category: 'workshop',
    size: 'medium',
    source: 'system',
    footprint: '14 × 17',
    objectCount: 21,
    estimatedCost: '9,640 钱',
    description: '生产房、晒场、水缸与围合院落组合，保留内部作业空地和运输通道。',
    previewAsset: '/assets/wanhu-gameplay-city.png',
    previewPosition: '72% 54%',
    previewSize: '530px auto',
  },
  {
    id: 'bp-workshop-carpenter-yard',
    name: '木作工坊',
    category: 'workshop',
    size: 'small',
    source: 'workshop',
    footprint: '9 × 13',
    objectCount: 13,
    estimatedCost: '5,320 钱',
    description: '小型木作生产院，包含作业棚、原料堆场和简易围墙，适合散布在手工业街区。',
    previewAsset: '/assets/wanhu-main-menu.png',
    previewPosition: '34% 50%',
    previewSize: '520px auto',
  },
  {
    id: 'bp-administration-patrol',
    name: '里坊巡检所',
    category: 'administration',
    size: 'small',
    source: 'system',
    footprint: '9 × 11',
    objectCount: 10,
    estimatedCost: '6,180 钱',
    description: '面向街口的小型治理节点，包含值房、院门和短围墙，可作为坊内治安设施。',
    previewAsset: '/assets/wanhu-gameplay-city.png',
    previewPosition: '57% 38%',
    previewSize: '520px auto',
  },
  {
    id: 'bp-administration-storage-office',
    name: '仓曹小院',
    category: 'administration',
    size: 'medium',
    source: 'mine',
    footprint: '13 × 16',
    objectCount: 17,
    estimatedCost: '10,240 钱',
    description: '办公厅房、档案仓与独立院落组合，适合中等规模官署区的辅助节点。',
    previewAsset: '/assets/wanhu-main-menu.png',
    previewPosition: '70% 48%',
    previewSize: '540px auto',
  },
  {
    id: 'bp-science-school',
    name: '蒙学书院',
    category: 'science',
    size: 'medium',
    source: 'system',
    footprint: '14 × 18',
    objectCount: 19,
    estimatedCost: '11,460 钱',
    description: '讲堂、两侧斋舍和安静庭院组成的小型书院，适合文教街区与居民区交界处。',
    previewAsset: '/assets/wanhu-gameplay-city.png',
    previewPosition: '38% 40%',
    previewSize: '550px auto',
  },
  {
    id: 'bp-science-observatory',
    name: '观星小院',
    category: 'science',
    size: 'small',
    source: 'workshop',
    footprint: '8 × 10',
    objectCount: 8,
    estimatedCost: '5,880 钱',
    description: '小型观测台与值房组成的研究节点，强调开阔天空和较少遮挡。',
    previewAsset: '/assets/wanhu-gameplay-lake.png',
    previewPosition: '34% 34%',
    previewSize: '500px auto',
  },
  {
    id: 'bp-faith-earth-shrine',
    name: '土地祠院',
    category: 'faith',
    size: 'small',
    source: 'system',
    footprint: '7 × 9',
    objectCount: 7,
    estimatedCost: '3,760 钱',
    description: '主殿、短墙和古树构成的社区祠院，可嵌入街坊边角或村落入口。',
    previewAsset: '/assets/wanhu-gameplay-city.png',
    previewPosition: '20% 42%',
    previewSize: '500px auto',
  },
  {
    id: 'bp-faith-waterside-temple',
    name: '水岸禅院',
    category: 'faith',
    size: 'large',
    source: 'workshop',
    footprint: '20 × 26',
    objectCount: 33,
    estimatedCost: '21,800 钱',
    description: '主殿、偏殿、院墙与水岸园景组成的完整寺观组团，适合城市边缘和滨水景观节点。',
    previewAsset: '/assets/wanhu-gameplay-lake.png',
    previewPosition: '54% 48%',
    previewSize: '570px auto',
  },
  {
    id: 'bp-military-watch-post',
    name: '箭楼营房',
    category: 'military',
    size: 'medium',
    source: 'system',
    footprint: '13 × 17',
    objectCount: 20,
    estimatedCost: '14,620 钱',
    description: '箭楼、营房与围合场地组成的城防驻点，可沿城墙或重要道路布置。',
    previewAsset: '/assets/wanhu-main-menu.png',
    previewPosition: '78% 42%',
    previewSize: '560px auto',
  },
  {
    id: 'bp-military-training-yard',
    name: '练兵小营',
    category: 'military',
    size: 'large',
    source: 'mine',
    footprint: '22 × 24',
    objectCount: 25,
    estimatedCost: '18,900 钱',
    description: '营房围绕训练空地布置，内部保持大面积无障碍空间，适合作为城郊军事节点。',
    previewAsset: '/assets/wanhu-gameplay-city.png',
    previewPosition: '82% 64%',
    previewSize: '580px auto',
  },
  {
    id: 'bp-palace-ceremonial-court',
    name: '三进礼院',
    category: 'palace',
    size: 'large',
    source: 'system',
    footprint: '24 × 34',
    objectCount: 42,
    estimatedCost: '38,600 钱',
    description: '三进轴线院落与附属廊庑组成的大型礼制建筑群，用于重要官署或宫苑节点。',
    previewAsset: '/assets/wanhu-main-menu.png',
    previewPosition: '50% 36%',
    previewSize: '620px auto',
  },
  {
    id: 'bp-palace-princely-front',
    name: '王府前院',
    category: 'palace',
    size: 'large',
    source: 'workshop',
    footprint: '26 × 32',
    objectCount: 38,
    estimatedCost: '35,240 钱',
    description: '门厅、前殿、左右配房与完整前院组成的高等级建筑组合，强调中轴和对称关系。',
    previewAsset: '/assets/wanhu-main-menu.png',
    previewPosition: '62% 37%',
    previewSize: '610px auto',
  },
];
